apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  credentials: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZCA9IEFLSUFUM1VJVlJBTUxXSzNXNlRXDQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBWdTJxNitFR3BYcGRKdDZjSitFN1RJZHhsTXlSMGt2YXROV0lwRkFxDQo=